version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: equinox_project_db_container
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: equinox_ollama_container
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_ORIGINS=*
    # If you have an NVIDIA GPU and want to enable GPU acceleration for Ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # or 'all'
              capabilities: [gpu]

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  default:
    name: equinox_network 